# -*- coding: utf-8 -*-
"""Linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EehD3CnDLYxUf-9nOpSqLCPpJoDkVr0S
"""

import pandas as pd
import statsmodels.api as sm

df = pd.read_csv("/content/cleaned_data.csv")
print(df.head())
print(df.info())

# Update X to include multiple independent variables
X = df[['Median income (dollars)', 'density(/hectare)', 'Nearest distance (km)']]
y = df['Average vehicle']
# Re-run the regression model
X = sm.add_constant(X)  # Add a constant term for intercept
m = sm.OLS(y, X).fit()

print(m.summary())